spring:
  application:
    name: API-GATEWAY

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl: http://localhost:8761/eureka
        registry:
          auto-registration: true

    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=1

        - id: HOTEL-RATING-SERVICE
          uri: lb://HOTEL-RATING-SERVICE
          predicates:
            - Path=/api/ratings/**
          filters:
            - StripPrefix=1

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
